# Stripe / flutter_stripe push provisioning (adding a card to Google/Apple
# Pay wallets) — an optional feature this app doesn't use. flutter_stripe
# shares native Android code with the react-native-stripe-sdk, and its
# push-provisioning code path references classes that only ship if you pull
# in Stripe's separate push-provisioning dependency. Since we don't use that
# feature, R8 just needs to be told it's safe that these are missing.
#
# Auto-generated by the Android Gradle plugin after a failed release build,
# copied from build/app/outputs/mapping/release/missing_rules.txt. If
# flutter_stripe adds more optional classes in a future version and the
# build fails again with "Missing classes detected while running R8", check
# that file again and append any new lines here.
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider
